version: '2'
services:
  nginx:
    image: nginx
    volumes:
     - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
     - .:/var/www/html
    ports:
     - 80:80
    networks:
     - lurn-central-net
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: cmarius/php
    volumes:
     - .:/var/www/html
    networks:
     - lurn-central-net
  mysql:
     image: mysql:5.7.21
     volumes:
      - mysqldata:/var/lib/mysql
     ports:
      - 3306:3306
     networks:
      - lurn-central-net
     environment:
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_DATABASE=lurn-central"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
  node:
      build:
        context: ./docker/node
        dockerfile: Dockerfile
      image: cmarius/node
      volumes:
       - .:/var/www/html
      networks:
       - lurn-central-net
      working_dir: /var/www/html
      tty: true
  redis:
      image: redis:3.2.11-alpine
      ports:
       - 6379:6379
      networks:
       - lurn-central-net
networks:
  lurn-central-net:
    driver: "bridge"
volumes:
  mysqldata:
