@extends('layouts.home')

@section('content')
    <section id="about-page">
        <div class="wrapper">
            <div class="box">
                <h2 class="title">
                    Terms Of Use
                </h2>
                <hr class="mt-30">
                <p>Yes, there's lots of legal stuff on this page, but we're required to share it with you. And that's a good thing, because at Lurn we believe you should be an informed consumer and user of the Internet.</p>
                <p>The terms and conditions below (the "terms") are what govern your use of the Lurn website on the Internet  and World Wide Web. These terms are a legal contract between you and Lurn.com  (“we” or “us”.) They govern your access to, and your use of our website, which (as you know) is located at Lurn.com (the “site”). These terms also govern your use of any services and products we provide on the site. If you do not agree with any of these terms, please do not access or otherwise use this site and/or our services and products.</p>
                <p>Your use of this site, services and/or products on this site means that you agree to abide by each of the terms below. Lurn.com may make changes to the services and products offered on this site, at any time and without notice, and Lurn.com can change these terms at any time without notice by posting updated terms of use here on the site.</p>
                <p>If you continue to use the site after such changes have been posted, it means that you agree to the new terms, even if you have not reviewed the changes. Therefore you really should check the terms of use posted here periodically for updates and changes.</p>
                <h3 class="spacer top">Privacy Policy</h3>
                <p>Your use of the site is governed by the Lurn.com <a href="{{ route('privacy') }}">Privacy Policy</a>, which is available on this site on our <a href="{{ route('privacy') }}">Privacy Policy</a> page.</p>
                <h3 class="spacer top">General  Use</h3>
                <p>Lurn.com provides content, services and products throughout this site. All information, documents, products and services, including content, trademarks, logos, graphics and images (which  are grouped together under the term “Materials”) are the copyrighted work of Lurn.com or Lurn.com's licensors and/or contributors.</p>
                <p>Lurn.com grants you a limited, personal, non-exclusive and non-transferable license to use the Materials solely for your personal use or internal business use. You agree that you will only use this site and the Materials for lawful uses.</p>
                <p>You agree that you have no right to modify, edit, copy, reproduce, create derivative works of, alter, enhance or in any way exploit any of the Materials provided by Lurn.com in any manner. Your limited license terminates automatically, without notice to you, if you breach any of these terms.</p>
                <p>Upon termination of your limited license, you agree to immediately destroy any downloaded or printed Materials. Except as stated herein, you acknowledge that you have no right, title or  interest in or to the site or any Materials on any legal basis.</p>
                <p>You are prohibited from taking any action to circumvent or attempt to circumvent the security and access control provisions of the site. Such prohibited conduct includes, but is not  limited to, any efforts to: (a) log into an account with a password not assigned to you; (b) access personally identifiable information not intended for you; (c) test the security measures on the site and/or attempt to identify system vulnerabilities; (d) impersonate any other user of the site and/or the products and services, forge any of the header information in any posting, or tamper with the TCP/IP packet header; (d) modify, reverse engineer,  disassemble, decompile or otherwise attempt or allow others to attempt to discover the underlying software code for the site and/or the products and services; or (f) overwhelm or disable the site or the products and services or interfere with the access and use of the site and/or the services by any other user.</p>
                <p>If Lurn.com becomes aware of any of the aforementioned activities on your part, we may investigate and take action. When appropriate, we may work with law enforcement to investigate and prosecute offenders.</p>
                <p>Your continued use of the Site and/or the products and services is expressly conditioned on your compliance with the prohibitions, obligations and restrictions just stated. Without limiting the foregoing, you acknowledge that Lurn.com prohibits and you agree not to:</p>
                <ul>
                    <li>Take any action that imposes an unreasonable or disproportionately large burden on the site's infrastructure;</li>
                    <li>Intentionally expose the site and/or any products or services provided on Lurn.com to a computer virus or any other program or code that is intended to disrupt or disable the operations of the site and/or our products or services;</li>
                    <li>Frame or link to the site or any of the content or information available from the site, unless Lurn.com expressly consents to such linking and/or framing;</li>
                    <li>Use any spider, robot or other program, code or device to copy, retrieve or index any portion of the Lurn.com site;</li>
                    <li>Harvest or otherwise collect information about other users for any purpose other than expressly permitted herein;</li>
                    <li>Post any false or inaccurate Submissions (defined below) or information on any part of the site;</li>
                    <li>Use the products and/or services and/or the site to violate any applicable law or regulation, including, without limitation, the infringement of any copyright, trademark, trade secret or other intellectual property rights, or violate the privacy or rights of any other person;</li>
                    <li>Post any Submission or information that is discriminatory, hateful, obscene, vulgar, abusive, defamatory, sexually-orientated, threatening, or otherwise objectionable;</li>
                    <li>Include any hyperlinks or any misleading, irrelevant and/or hidden code or keywords in any Submissions posted by you;</li>
                    <li>Harass, stalk, or otherwise subject any other user of the site and/or products and services to inappropriate or unwanted contact;</li>
                    <li>Make any additions, changes, alterations and/or deletions to any Submissions posted by any user without the express written authorization of such other user;</li>
                    <li>Lurn.com reserves the right to terminate our relationship with you under these terms and prohibit your access to the site and/or products or services or to edit, remove or close any Submission or thread for any reason.</li>
                </ul>
                <p>The foregoing list of prohibitions is illustrative and is not intended to be complete or exclusive.</p>
                <p>You acknowledge and agree that there is the chance that you may be exposed to content that may be offensive or objectionable to you. You hereby acknowledge and agree that all submissions submitted by you or any other user express the views of the author, and Lurn.com will not be held responsible for or liable for the content in such submissions.</p>
                <p>Your access to the site and Services is undertaken at your own risk and Lurn.com is not responsible for any offensive or otherwise objectionable materials that may be posted by any third party.</p>
                <p>In addition, the foregoing prohibitions do not impose on Lurn.com any obligation to monitor or remove any Submissions or other information or communication submitted by you or any other user.</p>
                <h3 class="spacer top">Submissions</h3>
                <p>Subject to the terms and conditions of the Lurn.com Privacy Policy, when you submit data and/or post communications on the site (collectively “Submissions”), you grant to Lurn.com and Lurn, Inc. an irrevocable, perpetual, royalty-free, worldwide right (including moral right) and license to use, reproduce, display, distribute, modify and create derivative works of Submissions, in whole or in  part, and to incorporate Submissions into other works in any media and utilizing any technology now known or later developed. You warrant that you have all rights, and no third party has retained any such rights, (including moral rights) in and to Submissions you may post to the site.</p>
                <h3 class="spacer top">Password Restricted Areas of the Website</h3>
                <p>Certain areas of the site may be password-restricted so only authorized users can access certain web pages and services (“Restricted Areas”).</p>
                <p>If you are an authorized member of the Restricted Areas, you take responsibility for maintaining the confidentiality of your password and account. You agree to notify Lurn.com if your password may have been compromised, or is lost, stolen, or disclosed to an unauthorized third party.</p>
                <p>You agree to immediately notify Lurn.com of any unauthorized use of your account or any other breach of security in relation to the site that may be known to you. You are responsible for activities that occur under your account.</p>
                <h3 class="spacer top">Links to Third Party Sites</h3>
                <p>The Lurn.com site may be linked to other sites that are not owned, operated, or managed by Lurn. We provide these links to you only as a convenience, and Lurn.com is not responsible for the content or links displayed on these third party sites.</p>
                <h3 class="spacer top">Third Party Content</h3>
                <p>Some information and content may be provided by third parties to Lurn.com (“Third Party  Content”). The Third Party Content is the copyrighted work of the creator/licensor, Lurn.com, and Lurn, Inc.</p>
                <p>You agree that you will only display the Third Party Content on your personal computer for your personal or internal business use. You acknowledge and agree that you have no right to download, cache, reproduce, modify, display (except as set forth in this paragraph), alter, edit, manipulate or enhance any of the Third Party Content in any manner.</p>
                <p>Lurn.com disclaims all express, implied and statutory warranties and conditions with regard to third party content. This includes, but is not limited to, all implied warranties of merchantability, fitness for a particular purpose and non-infringement.</p>
                <h3 class="spacer top">Unauthorized Activities</h3>
                <p>Unauthorized use of any Materials or Third Party Content contained on this site may violate certain regulations and laws. You shall indemnify and hold Lurn.com and its officers, directors, employees, affiliates, agents, licensors, and business partners harmless from and against any and all damages, costs, expenses, and liabilities, including attorneys' fees, that Lurn.com or any other indemnified  party suffers in relation to, arising from, or for the purpose of avoiding any claim or demand from a third party in the event that your use of the site or the use of the site by any person using your user name and/or password violates any applicable law or regulation, or the rights of any third party.</p>
                <h3 class="spacer top">Copyright Notice</h3>
                <p>All information, data, and screens appearing on Lurn.com, including web pages, documents, site design, text, graphics, logos, images and icons, and the selection and arrangement thereof, are the sole property of Lurn.com and Lurn, Inc. unless otherwise specified.</p>
                <p>All rights not expressly granted herein are reserved worldwide. Any reproduction, distribution, modification, retransmission, or publication of any copyrighted  material on the site is strictly prohibited without the express written consent of the copyright holder, except as otherwise required by applicable law.</p>
                <h3 class="spacer top">Disclaimer of Warranties</h3>
                <p>Your use of this site, the Materials and/or the products and services is at your own risk. You assume all risks of using this site, the Materials and/or the products and services. Lurn.com does not warrant the accuracy or timeliness of the materials or the Third Party Content contained on this Site. Neither the Materials nor the Third Party Content have been verified or authenticated in whole or in part by Lurn.com, and they may not be current or may include inaccuracies or typographical errors.</p>
                <p>Lurn.com shall have no liability for Materials and/or Third Party Content that is not current or for any errors or omissions in the Materials and/or the Third Party Content, whether provided by Lurn.com or our licensors. Lurn.com does not guarantee that you will achieve any economic return or benefit from the use of  the Materials.</p>
                <p>Lurn.com, for itself and its licensors, makes no express, implied or statutory representations, warranties, or guarantees in connection with the site, the products and services or any Materials or Third Party Content, relating to the quality, suitability, truth, accuracy, currency or completeness of any information or material contained on the site. This includes, without  limitation, the Materials and the Third Party Content. </p>
                <p>Lurn.com disclaims and excludes any and all implied warranties, including any implied warranty of merchantability, fitness for a particular purpose, or non-infringement of third party rights. Unless otherwise explicitly stated, to the maximum extent permitted by applicable law, the site, the products and services, the Materials, Third Party Content, and any information or material contained on the site is provided to you on an “as is,” “as available” and “where is” basis with no warranty of any kind.</p>
                <h3 class="spacer top">Limitation of Liability</h3>
                <p>In no event shall Lurn.com be liable to you or any third party for any indirect, extraordinary, exemplary, punitive, special, incidental, or consequential damages (including loss of data, revenue, profits, use or other economic advantage) however arising, even if Lurn.com and Lurn, Inc. have been advised of the possibility of such damage.</p>
                <p>Lurn.com's aggregate liability to you or any third party for any damages resulting from  your displaying, copying, or downloading any material on the site or reliance on the information and/or material presented on the site shall not exceed fifty dollars ($50.00).</p>
                <h3 class="spacer top">Local Laws and Export Control</h3>
                <p>If you use this site outside the United States of America, you are responsible for compliance with all applicable local laws. Lurn.com controls and operates this site from its headquarters in the United States of America and the Materials may not be appropriate or available for use in other locations.</p>
                <h3 class="spacer top">Consequences of Violation</h3>
                <p>If you violate these terms, Lurn.com may terminate your access to the site or Password-Restricted Areas without notice. Lurn.com prefers to advise you of your inappropriate behavior and recommend any necessary corrective action. However, certain violations of these terms, as determined by Lurn.com, will result in immediate termination of your access to the site or Password-Restricted Areas.</p>
                <p>Lurn.com reserves the right to terminate any password-restricted account for any reason. These terms are governed by Maryland Law and controlling U.S. Federal Law, without regard to the choice or conflicts of law provisions. Any disputes  relating to these terms or the site will be heard in courts located in Maryland. If any of these terms is found to be inconsistent with applicable law, then such terms shall be interpreted to reflect the intentions of the parties, and no other terms will be modified.</p>
                <p>Lurn.com's failure to enforce any of these terms is not a waiver of such terms. These terms are the entire agreement between you and Lurn.com and supersede any and all prior or contemporaneous agreements and understandings between you and Lurn.com and Lurn, Inc. These terms may not be modified except pursuant to a written amendment that is executed by an officer of Lurn.com and Lurn, Inc.</p>
            </div>
        </div>
    </section>
@endsection
