@extends('admin.layout')

@section('pagetitle')
    Stats
    <small>Total stats</small>
@endsection

@section('breadcrumb')
    <li>
        <i class="fa fa-area-chart"></i>
        <a href="{{ route('stats.index') }}">Stats</a>
    </li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-6">
            <form action="{{ route('stats.average') }}" method="post">
                {{ csrf_field() }}

                <table class="table table-bordered table-striped">
                    <tr>
                        <th><h4><strong>Total Daily User Revenue Reporting</strong></h4></th>
                    </tr>
                    <tr>
                        <td>
                            <p>
                                This calculation will retrieve the total number of sales generated in the stated time period, for all users who have been a Lurn Nation member for that time period, and divide the total sales by the number of registered members for that time period.<br>
                                <a href="#" onclick="alert('If you enter 10, the calculation will report the total number of sales generated by all users in the first 10 days post registration and divide it by the number of users that exist in Lurn Nation that are at least 10 days old')">Explain this.</a>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label><strong>Number of Days to Report</strong></label>
                            <div>
                                <div class="input-group">
                                    <input type="number" class="form-control" min="1" name="days" value="30">
                                    <span class="input-group-btn">
                                        <button class="btn blue">Report</button>
                                    </span>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>

        <div class="col-md-6">
            <form action="{{ route('stats.detailed') }}" method="post">
                {{ csrf_field() }}

                <table class="table table-bordered table-striped">
                    <tr>
                        <th><h4><strong>Per User Revenue Reporting</strong></h4></th>
                    </tr>
                    <tr>
                        <td><p>This option will show a per user or per country breakdown of the other option.</p></td>
                    </tr>
                    <tr>
                        <td>
                            <label><strong>Number of Days to Report</strong></label>
                            <div>
                                <div class="input-group">
                                    <span class="input-group-addon" style="padding: 0; width: 120px; border: none;">
                                        <select name="type" class="form-control">
                                            <option value="user">Per User</option>
                                            <option value="countries">Per Country</option>
                                        </select>
                                    </span>
                                    <input type="number" class="form-control" min="1" name="days" value="30">
                                    <span class="input-group-btn">
                                        <button class="btn blue">Report</button>
                                    </span>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
@endsection

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.8.0/css/flag-icon.min.css" rel="stylesheet"
          type="text/css">
@endsection
