<?php
/**
 * @file
 * Code for FB Likebox module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fb_likebox_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.fb_likebox':
      $help_text = '<p>' . t("This module provides provides a configurable block with Facebook Likebox's plugin.") . '</p>';
      return $help_text;
  }
}

/**
 * Implements hook_theme().
 */
function fb_likebox_theme() {
  return [
    'fb_likebox_block' => [
      'variables' => [
        'fb_url' => NULL,
        'fb_colorscheme' => NULL,
        'fb_header' => NULL,
        'fb_stream' => NULL,
        'fb_show_faces' => NULL,
        'fb_force_wall' => NULL,
        'fb_width' => NULL,
        'fb_height' => NULL,
        'fb_show_border' => NULL,
      ],
      'template' => 'fb_likebox_block',
    ],
  ];
}
